site_name: TP-Link router hard reset
site_url: https://josh-wong.github.io/tplink-router-hard-reset/
site_description: A tutorial that describes how to perform a hard reset on a TP-Link Wi-Fi router.

# Add repo details in the top right-hand corner
repo_name: josh-wong/tplink-router-hard-reset
repo_url: https://github.com/josh-wong/tplink-router-hard-reset/
edit_uri: blob/main/docs

plugins:
  - search
  - minify:
      minify_html: true
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  # Enables TechDocs support in Backstage. However, many plugins need to be disabled for TechDocs to work properly.
  #- techdocs-core

markdown_extensions:
  # Add support for abbreviations
  - abbr
  # Add support for Material for MkDocs admonitions
  - admonition
  # Add styles for buttons
  - attr_list
  # Add support for grid cards
  - md_in_html
  # Make admonitions collapsible
  - pymdownx.details
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add tooltip support
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/glossary.md
  # Add support for arbitrary nesting of code and content blocks inside each other.
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  # Add support for TOC configuration
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  # Extend the theme
  #custom_dir: overrides
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_tplink_router_logo.png
  icon:
    # Add icon to show repository information and link
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue grey
      accent: blue
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: blue grey
      accent: blue
  features:
    # Mark announcement as read
    - announce.dismiss
    # Add support for improved tooltips
    - content.tooltips
    # Add custom search functions
    - search.highlight
    - search.share
    - search.suggest
    # Add custom navigation functions
    - navigation.expand
    - navigation.footer
    #- navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra:
  analytics:
    provider: google
    property: G-PMP34RZWN2
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help me improve this page by <a href="https://github.com/josh-wong/tplink-router-hard-reset/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">creating an issue in GitHub</a>.
  consent:
    title: Cookie consent
    description: >- 
      This site uses cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of the documentation and whether users find what they're searching for. With your consent, you're helping to improve this documentation and provide a better user experience.
    actions:
      - accept
      - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/josh-wong
      name: josh-wong on GitLab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://famichiki.jp/@josh
      name: josh on Mastodon
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/hex080f53
      name: hex080f53 on Steam
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/080f53
      name: 080f53 on Twitter
  status:
    new: Recently added
    deprecated: Deprecated

extra_css:
  - stylesheets/extra.css

copyright: >
  &copy; 2021-2023 Josh Wong –
  <a href="#__consent">🍪Cookie settings</a>

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Performing a hard reset of the router: '02_performing-a-hard-reset-of-the-router.md'
  - Conclusion: '03_conclusion.md'
  - Contributions: '04_contributions.md'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'