site_name: How to perform a hard reset of a TP-Link Wi-Fi router
site_url: https://josh-wong.github.io/zune-software-setup

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/mkdocs_tplink_router_logo.png
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: blue


nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Performing a hard reset of the router: '02_performing-a-hard-reset-of-the-router.md'
  - Conclusion: '03_conclusion.md'
  - Contributions: '04_contributions.md'
  - Donations: '05_donations.md'
  - 🏠return to josh-wong: 'https://josh-wong.github.io/'