site_name: How to perform a hard reset of a TP-Link Wi-Fi router
site_url: https://josh-wong.github.io/zune-software-setup

repo_name: josh-wong/tplink-router-hard-reset
repo_url: https://github.com/josh-wong/tplink-router-hard-reset
# want to eventually hide the edit button since there's a conflict between editing the 
# multirepo docs site and the individual docs site
edit_uri: edit/main/

plugins:
  - search

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/mkdocs_tplink_router_logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: blue
      accent: blue
  features:
    - search.suggest

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Performing a hard reset of the router: '02_performing-a-hard-reset-of-the-router.md'
  - Conclusion: '03_conclusion.md'
  - Contributions: '04_contributions.md'
  - Donations: '05_donations.md'