site_name: How to perform a hard reset of a TP-Link Wi-Fi router
site_url: https://josh-wong.github.io/tplink-router-hard-reset/
site_description: A tutorial that describes how to perform a hard reset on a TP-Link Wi-Fi router.

# Add repo details in the top right-hand corner
repo_name: josh-wong/tplink-router-hard-reset
repo_url: https://github.com/josh-wong/tplink-router-hard-reset/
edit_uri: blob/main/docs

plugins:
  - search
  # Enables TechDocs support in Backstage. However, many plugins need to be disabled for TechDocs to work properly.
  #- techdocs-core
  # Show the last updated date
  - git-revision-date-localized:
      type: date
  # Enable videos to be embedded
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  # Enable support for social cards (pretty link previews)
  - social

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  # Extend the theme
  #custom_dir: overrides
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_tplink_router_logo.png
  icon:
    # Add icon to show repository information and link
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: cyan
      accent: blue
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: cyan
      accent: blue
  features:
    # Mark announcement as read
    - announce.dismiss
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Performing a hard reset of the router: '02_performing-a-hard-reset-of-the-router.md'
  - Conclusion: '03_conclusion.md'
  - Contributions: '04_contributions.md'
  - '': ''
  - 🔶RSS: 'https://josh-wong.github.io/tplink-router-hard-reset/feed_rss_updated.xml'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'