name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # This token expires on ____, 2023.
      - run: pip install \ 
          git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git \
          mkdocs-video \
          mkdocs-git-revision-date-localized-plugin \
          python-slugify \
          mkdocs-git-committers-plugin-2==1.0.1 \
      #- run: mkdocs build --config-file mkdocs.insiders.yml
      - run: mkdocs gh-deploy --force
env:
  # This token expires on _____, 2023.
  GH_TOKEN: ${{ secrets.GH_TOKEN }}